version: '3.3'
services:
  app:
    container_name: kucchil-kitchen-app-container
    image: kucchil-kitchen-app-image
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: kucchil-kitchen-db
    image: library/postgres:10.12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres