version: '3.3'
services:
  app:
    container_name: kucchil-kart-app-container
    image: kucchil-kart-app-image
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: kucchil-kart-db
    image: library/postgres:10.12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Hr05q4482!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=retail